# Generated by Django 5.1.1 on 2024-11-14 03:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalComunicacion',
            fields=[
                ('id_canal', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_canal', models.CharField(max_length=50)),
                ('prioridad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('tipo_producto', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id_usuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña_hash', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dueño',
            fields=[
                ('id_dueño', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('teléfono', models.CharField(max_length=15)),
                ('dirección', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=50)),
                ('país', models.CharField(max_length=50)),
                ('región', models.CharField(max_length=50)),
                ('compras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dueños', to='app.compra')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('nacimiento', models.DateField()),
                ('ultima_consulta', models.DateField(blank=True, null=True)),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='app.dueño')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_consulta', models.DateField()),
                ('motivo', models.TextField()),
                ('diagnóstico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='app.mascota')),
                ('productos', models.ManyToManyField(related_name='consultas', to='app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id_recordatorio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('frecuencia', models.CharField(max_length=50)),
                ('canal', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='app.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_agenda', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(max_length=50)),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.mascota')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.usuariosistema')),
            ],
        ),
    ]
