# Generated by Django 5.1.1 on 2024-11-14 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
