# Generated by Django 5.1.1 on 2024-11-25 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mascota'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuariosistema'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='consultas', to='app.producto'),
        ),
    ]
