# Generated by Django 5.1.1 on 2024-11-25 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_agenda_mascota_alter_agenda_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='usuario',
        ),
    ]
